environment:
  nuget_version: '0.2.0-alpha4'
  assembly_version: '1.0.0'

clone_depth: 5

pull_requests:
  do_not_increment_build_number: true

version: '$(nuget_version)+{build}'
configuration: Release

assembly_info:
  patch: true
  file: src\**\Properties\AssemblyInfo.cs
  assembly_version: '$(assembly_version)'

build_script:
- cmd: >-
    powershell -f build.ps1 -CI -Version "%NUGET_VERSION%" -Configuration %CONFIGURATION%"
artifacts:
- path: Build\*.nupkg

test: off

